"""Scope the live site's stylesheets (~/njmc-site/assets/*.css) under .legacy so the imported
page bodies keep their look without touching the new header and footer. :root, @font-face and
@keyframes pass through unchanged; html/body selectors map to .legacy itself."""
import pathlib, re
SRC = pathlib.Path.home() / 'njmc-site' / 'assets'
OUT = pathlib.Path(__file__).resolve().parent.parent / 'src' / 'app' / 'legacy.css'

def scope_selectors(sel: str) -> str:
    out = []
    for s in sel.split(','):
        s = s.strip()
        if not s:
            continue
        if s.startswith(':root'):
            out.append(s)
        elif re.match(r'^(html|body)\b', s):
            out.append('.legacy' + re.sub(r'^(html|body)', '', s))
        elif s.startswith('[dir'):
            m = re.match(r'(\[dir=?"?rtl"?\])\s*(.*)', s)
            out.append(f'[dir="rtl"] .legacy {m.group(2)}' if m and m.group(2) else '[dir="rtl"] .legacy')
        else:
            out.append('.legacy ' + s)
    return ', '.join(out)

def scope(css: str) -> str:
    css = re.sub(r'/\*.*?\*/', '', css, flags=re.S)
    res, i = [], 0
    while i < len(css):
        j = css.find('{', i)
        if j < 0:
            break
        head = css[i:j].strip()
        if head.startswith('@media') or head.startswith('@supports'):
            depth, k = 1, j + 1
            while depth:
                depth += {'{': 1, '}': -1}.get(css[k], 0); k += 1
            res.append(head + '{' + scope(css[j + 1:k - 1]) + '}')
            i = k; continue
        if head.startswith('@'):
            depth, k = 1, j + 1
            while depth:
                depth += {'{': 1, '}': -1}.get(css[k], 0); k += 1
            res.append(css[i:k]); i = k; continue
        k = css.find('}', j)
        res.append(scope_selectors(head) + '{' + css[j + 1:k] + '}')
        i = k + 1
    return '\n'.join(res)

parts = ['/* Generated by scripts/scope-legacy-css.py from the live site CSS. Do not edit by hand. */']
for name in ('njmc-home.css', 'njmc-pages.css'):
    parts.append(f'/* {name} */\n' + scope((SRC / name).read_text('utf-8')))
out = '\n'.join(parts) + '\n'
# The new site uses self-hosted IBM Plex (docs/01); drop the old Google-hosted faces.
out = re.sub(r"font-family:\s*'(Inter|Playfair Display)',\s*(sans-serif|serif)", 'font-family: inherit', out)
OUT.write_text(out, 'utf-8')
print(OUT, OUT.stat().st_size)
