/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    leads: Lead;
    products: Product;
    suppliers: Supplier;
    'supplier-certificates': SupplierCertificate;
    'order-matches': OrderMatch;
    'order-files': OrderFile;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    suppliers: SuppliersSelect<false> | SuppliersSelect<true>;
    'supplier-certificates': SupplierCertificatesSelect<false> | SupplierCertificatesSelect<true>;
    'order-matches': OrderMatchesSelect<false> | OrderMatchesSelect<true>;
    'order-files': OrderFilesSelect<false> | OrderFilesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'ar') | ('en' | 'ar')[];
  globals: {};
  globalsSelect: {};
  locale: 'en' | 'ar';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  type: 'rfq' | 'verification';
  status?: ('new' | 'replied' | 'quoted' | 'won' | 'closed') | null;
  name: string;
  company?: string | null;
  role?: string | null;
  country: string;
  email: string;
  /**
   * Phone or WhatsApp
   */
  phone?: string | null;
  service?: string | null;
  /**
   * Verification orders: supplier or product to check
   */
  supplier?: string | null;
  message: string;
  heardAbout?: string | null;
  consent: boolean;
  page?: string | null;
  utmFirst?: string | null;
  utmLast?: string | null;
  /**
   * Notification reached the mail relay
   */
  emailed?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  /**
   * Web address: /catalogue/<slug>/ (lower case, hyphens)
   */
  slug: string;
  /**
   * Shown on the public catalogue
   */
  published?: boolean | null;
  category: 'api' | 'excipient' | 'colour';
  /**
   * Therapeutic class, or colour type
   */
  productClass?: string | null;
  otherNames?: string | null;
  cas?: string | null;
  ciNumber?: string | null;
  grades?: ('EP' | 'USP' | 'BP' | 'JP' | 'ChP' | 'IP' | 'In-house')[] | null;
  /**
   * Private: manufacturers and their documents for this product
   */
  sources?:
    | {
        supplier: number | Supplier;
        /**
         * e.g. CEP, US DMF, WC, EU GMP
         */
        documents?: string | null;
        /**
         * e.g. permitted in: India, EU, USA
         */
        marketStatus?: string | null;
        details?: string | null;
        id?: string | null;
      }[]
    | null;
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suppliers".
 */
export interface Supplier {
  id: number;
  name: string;
  nameLocal?: string | null;
  country: string;
  city?: string | null;
  address?: string | null;
  website?: string | null;
  email?: string | null;
  phone?: string | null;
  supplies?: ('api' | 'intermediate' | 'excipient' | 'colour' | 'device' | 'consumable' | 'other')[] | null;
  status?: ('new' | 'contacted' | 'samples' | 'qualified' | 'approved' | 'on-hold' | 'rejected') | null;
  /**
   * Where we met them, e.g. CPHI Shanghai 2026
   */
  source?: string | null;
  /**
   * Link to the Drive folder or files
   */
  documentsFolder?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Sort by "Valid until" to see what expires next.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supplier-certificates".
 */
export interface SupplierCertificate {
  id: number;
  /**
   * Filled in automatically
   */
  title?: string | null;
  supplier: number | Supplier;
  type:
    | 'cn-gmp'
    | 'cn-dml'
    | 'eu-gmp'
    | 'us-fda'
    | 'who-gmp'
    | 'cep'
    | 'us-dmf'
    | 'wc'
    | 'ipec-gmp'
    | 'iso-9001'
    | 'iso-13485'
    | 'iso-22000'
    | 'fssc-22000'
    | 'business-licence'
    | 'other';
  number?: string | null;
  issuer?: string | null;
  scope?: string | null;
  issued?: string | null;
  validUntil?: string | null;
  state?: string | null;
  /**
   * File name or Drive link of the copy we hold
   */
  sourceFile?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Attach a customer order (Excel, CSV, Word, PDF) or type the materials, then Save. The suppliers for each material appear in "Results".
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-matches".
 */
export interface OrderMatch {
  id: number;
  /**
   * e.g. customer name + date
   */
  title: string;
  customer?: string | null;
  status?: ('new' | 'suppliers contacted' | 'quoted' | 'won' | 'lost') | null;
  /**
   * Excel, CSV, Word, PDF (with text) or .txt
   */
  orderFile?: (number | null) | OrderFile;
  /**
   * Optional: one material per line, e.g. "Mesalazine EP 500 kg" or a CAS number
   */
  typedMaterials?: string | null;
  rematch?: boolean | null;
  matchedAt?: string | null;
  readNote?: string | null;
  /**
   * Suppliers found for each material
   */
  results?: string | null;
  lines?:
    | {
        requested?: string | null;
        cas?: string | null;
        grade?: string | null;
        quantity?: string | null;
        supplierCount?: number | null;
        matches?:
          | {
              supplier?: (number | null) | Supplier;
              product?: (number | null) | Product;
              matchedOn?: string | null;
              documents?: string | null;
              certificates?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Uploaded customer orders (private).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-files".
 */
export interface OrderFile {
  id: number;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'suppliers';
        value: number | Supplier;
      } | null)
    | ({
        relationTo: 'supplier-certificates';
        value: number | SupplierCertificate;
      } | null)
    | ({
        relationTo: 'order-matches';
        value: number | OrderMatch;
      } | null)
    | ({
        relationTo: 'order-files';
        value: number | OrderFile;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  type?: T;
  status?: T;
  name?: T;
  company?: T;
  role?: T;
  country?: T;
  email?: T;
  phone?: T;
  service?: T;
  supplier?: T;
  message?: T;
  heardAbout?: T;
  consent?: T;
  page?: T;
  utmFirst?: T;
  utmLast?: T;
  emailed?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  published?: T;
  category?: T;
  productClass?: T;
  otherNames?: T;
  cas?: T;
  ciNumber?: T;
  grades?: T;
  sources?:
    | T
    | {
        supplier?: T;
        documents?: T;
        marketStatus?: T;
        details?: T;
        id?: T;
      };
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suppliers_select".
 */
export interface SuppliersSelect<T extends boolean = true> {
  name?: T;
  nameLocal?: T;
  country?: T;
  city?: T;
  address?: T;
  website?: T;
  email?: T;
  phone?: T;
  supplies?: T;
  status?: T;
  source?: T;
  documentsFolder?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supplier-certificates_select".
 */
export interface SupplierCertificatesSelect<T extends boolean = true> {
  title?: T;
  supplier?: T;
  type?: T;
  number?: T;
  issuer?: T;
  scope?: T;
  issued?: T;
  validUntil?: T;
  state?: T;
  sourceFile?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-matches_select".
 */
export interface OrderMatchesSelect<T extends boolean = true> {
  title?: T;
  customer?: T;
  status?: T;
  orderFile?: T;
  typedMaterials?: T;
  rematch?: T;
  matchedAt?: T;
  readNote?: T;
  results?: T;
  lines?:
    | T
    | {
        requested?: T;
        cas?: T;
        grade?: T;
        quantity?: T;
        supplierCount?: T;
        matches?:
          | T
          | {
              supplier?: T;
              product?: T;
              matchedOn?: T;
              documents?: T;
              certificates?: T;
              id?: T;
            };
        id?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-files_select".
 */
export interface OrderFilesSelect<T extends boolean = true> {
  note?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}