/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'order-matches': OrderMatch;
    clients: Client;
    'supplier-orders': SupplierOrder;
    'buyer-documents': BuyerDocument;
    'trade-files': TradeFile;
    payments: Payment;
    products: Product;
    suppliers: Supplier;
    'supplier-certificates': SupplierCertificate;
    'order-files': OrderFile;
    leads: Lead;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'order-matches': {
      documents: 'trade-files';
    };
    clients: {
      sales: 'buyer-documents';
      payments: 'payments';
      documents: 'trade-files';
    };
    'buyer-documents': {
      payments: 'payments';
      documents: 'trade-files';
    };
    suppliers: {
      orders: 'supplier-orders';
      payments: 'payments';
      documents: 'trade-files';
    };
  };
  collectionsSelect: {
    'order-matches': OrderMatchesSelect<false> | OrderMatchesSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    'supplier-orders': SupplierOrdersSelect<false> | SupplierOrdersSelect<true>;
    'buyer-documents': BuyerDocumentsSelect<false> | BuyerDocumentsSelect<true>;
    'trade-files': TradeFilesSelect<false> | TradeFilesSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    suppliers: SuppliersSelect<false> | SuppliersSelect<true>;
    'supplier-certificates': SupplierCertificatesSelect<false> | SupplierCertificatesSelect<true>;
    'order-files': OrderFilesSelect<false> | OrderFilesSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'ar') | ('en' | 'ar')[];
  globals: {
    'trade-settings': TradeSetting;
    'accounts-overview': AccountsOverview;
  };
  globalsSelect: {
    'trade-settings': TradeSettingsSelect<false> | TradeSettingsSelect<true>;
    'accounts-overview': AccountsOverviewSelect<false> | AccountsOverviewSelect<true>;
  };
  locale: 'en' | 'ar';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Attach a customer order (Excel, CSV, Word, PDF) or type the materials, then Save. The suppliers table appears below, with an Excel download.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-matches".
 */
export interface OrderMatch {
  id: number;
  /**
   * e.g. customer name + date
   */
  title: string;
  customer?: string | null;
  /**
   * The client record, used for the proforma invoice
   */
  client?: (number | null) | Client;
  status?: ('new' | 'suppliers contacted' | 'quoted' | 'won' | 'lost') | null;
  /**
   * Excel, CSV, Word, PDF (with text) or .txt
   */
  orderFile?: (number | null) | OrderFile;
  /**
   * Optional: one material per line, e.g. "Mesalazine EP 500 kg" or a CAS number
   */
  typedMaterials?: string | null;
  rematch?: boolean | null;
  matchedAt?: string | null;
  readNote?: string | null;
  results?: string | null;
  lines?:
    | {
        requested?: string | null;
        cas?: string | null;
        grade?: string | null;
        quantity?: string | null;
        supplierCount?: number | null;
        matches?:
          | {
              supplier?: (number | null) | Supplier;
              product?: (number | null) | Product;
              matchedOn?: string | null;
              documents?: string | null;
              certificates?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  notes?: string | null;
  documents?: {
    docs?: (number | TradeFile)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Companies we sell to. Their documents, sales and payments are listed on each client.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  /**
   * In English, as it must appear on the invoice
   */
  name: string;
  country?: string | null;
  registrationNo?: string | null;
  address?: string | null;
  contactPerson?: string | null;
  /**
   * Documents are sent here. Several addresses: separate with commas
   */
  email?: string | null;
  phone?: string | null;
  currency?: ('USD' | 'CNY' | 'EUR') | null;
  incoterm?: ('EXW' | 'FCA' | 'FOB' | 'CFR' | 'CIF' | 'CPT' | 'CIP' | 'DAP' | 'DDP') | null;
  /**
   * e.g. Aden
   */
  incotermPlace?: string | null;
  paymentTerms?: string | null;
  /**
   * Only if different from the client
   */
  consignee?: string | null;
  notifyParty?: string | null;
  notes?: string | null;
  sales?: {
    docs?: (number | BuyerDocument)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  payments?: {
    docs?: (number | Payment)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  documents?: {
    docs?: (number | TradeFile)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Fill in the buyer, the items and the prices once. The proforma invoice, the invoice and the packing list are printed from the same record.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "buyer-documents".
 */
export interface BuyerDocument {
  id: number;
  /**
   * Given automatically; you can change it
   */
  piNumber?: string | null;
  piDate?: string | null;
  validity?: string | null;
  status?:
    | ('draft' | 'PI sent' | 'confirmed' | 'paid' | 'in production' | 'shipped' | 'delivered' | 'closed' | 'cancelled')
    | null;
  /**
   * Given automatically when you fill in the invoice date. Also printed on the packing list
   */
  invoiceNumber?: string | null;
  /**
   * Fill in when the goods ship
   */
  invoiceDate?: string | null;
  buyerReference?: string | null;
  /**
   * Choose the client and save: the buyer details below fill in by themselves
   */
  client?: (number | null) | Client;
  /**
   * Several addresses: separate with commas
   */
  buyerEmail?: string | null;
  buyerName: string;
  buyerCountry?: string | null;
  buyerContact?: string | null;
  buyerAddress?: string | null;
  /**
   * Only if different from the buyer
   */
  consignee?: string | null;
  notifyParty?: string | null;
  items?:
    | {
        description: string;
        spec?: string | null;
        quantity?: number | null;
        unit?: string | null;
        unitPrice?: number | null;
        hsCode?: string | null;
        origin?: string | null;
        /**
         * Packing list
         */
        packages?: number | null;
        /**
         * e.g. 25 kg fibre drums
         */
        packageType?: string | null;
        netWeight?: number | null;
        grossWeight?: number | null;
        batchNo?: string | null;
        mfgDate?: string | null;
        expDate?: string | null;
        /**
         * In the currency of this document
         */
        costPrice?: number | null;
        costSupplier?: (number | null) | Supplier;
        costNote?: string | null;
        id?: string | null;
      }[]
    | null;
  currency?: ('USD' | 'CNY' | 'EUR') | null;
  incoterm?: ('EXW' | 'FCA' | 'FOB' | 'CFR' | 'CIF' | 'CPT' | 'CIP' | 'DAP' | 'DDP') | null;
  /**
   * e.g. Aden
   */
  incotermPlace?: string | null;
  /**
   * e.g. 100% T/T in advance
   */
  paymentTerms?: string | null;
  /**
   * Only if shown separately
   */
  freight?: number | null;
  insurance?: number | null;
  discount?: number | null;
  portOfLoading?: string | null;
  portOfDischarge?: string | null;
  shipmentBy?: ('Sea' | 'Air' | 'Courier' | 'Land') | null;
  /**
   * e.g. 30 days after payment
   */
  deliveryTime?: string | null;
  /**
   * Invoice and packing list
   */
  vessel?: string | null;
  blNumber?: string | null;
  shippingMarks?: string | null;
  remarks?: string | null;
  /**
   * For our records only
   */
  order?: (number | null) | OrderMatch;
  internalNotes?: string | null;
  readyDate?: string | null;
  etd?: string | null;
  eta?: string | null;
  forwarder?: string | null;
  documentsSent?:
    | (
        | 'Proforma invoice'
        | 'Commercial invoice'
        | 'Packing list'
        | 'Certificate of analysis'
        | 'Certificate of origin'
        | 'B/L or AWB copy'
        | 'Original documents by courier'
        | 'Insurance certificate'
      )[]
    | null;
  followUp?: string | null;
  sendLog?: string | null;
  payments?: {
    docs?: (number | Payment)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  documents?: {
    docs?: (number | TradeFile)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suppliers".
 */
export interface Supplier {
  id: number;
  name: string;
  nameLocal?: string | null;
  country: string;
  city?: string | null;
  address?: string | null;
  website?: string | null;
  email?: string | null;
  phone?: string | null;
  /**
   * Name and title, e.g. from the business card
   */
  contactPerson?: string | null;
  wechat?: string | null;
  supplies?: ('api' | 'intermediate' | 'excipient' | 'colour' | 'device' | 'consumable' | 'other')[] | null;
  status?: ('new' | 'contacted' | 'samples' | 'qualified' | 'approved' | 'on-hold' | 'rejected') | null;
  /**
   * Where we met them, e.g. CPHI Shanghai 2026
   */
  source?: string | null;
  /**
   * Link to the Drive folder or files
   */
  documentsFolder?: string | null;
  rating?: ('5' | '4' | '3' | '2' | '1') | null;
  problems?: string | null;
  notes?: string | null;
  orders?: {
    docs?: (number | SupplierOrder)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  payments?: {
    docs?: (number | Payment)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  documents?: {
    docs?: (number | TradeFile)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * An enquiry asks a supplier for prices. A purchase order orders the goods. Each one has a PDF and a message that is sent to the supplier only after you confirm.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supplier-orders".
 */
export interface SupplierOrder {
  id: number;
  /**
   * Given automatically
   */
  number?: string | null;
  kind: 'rfq' | 'po';
  status?: ('draft' | 'sent' | 'supplier replied' | 'confirmed' | 'cancelled') | null;
  date?: string | null;
  supplier: number | Supplier;
  /**
   * Taken from the supplier record; change it here if needed. Several addresses: separate with commas.
   */
  toEmail?: string | null;
  items?:
    | {
        material: string;
        spec?: string | null;
        quantity?: number | null;
        unit?: string | null;
        /**
         * Needed for a purchase order
         */
        unitPrice?: number | null;
        supplierProduct?: string | null;
        note?: string | null;
        /**
         * From the quotation page or their email
         */
        quotedPrice?: number | null;
        moq?: string | null;
        leadTime?: string | null;
        quoteNote?: string | null;
        requested?: string | null;
        id?: string | null;
      }[]
    | null;
  currency?: ('USD' | 'CNY' | 'EUR') | null;
  incoterm?: ('EXW' | 'FCA' | 'FOB' | 'CFR' | 'CIF' | 'CPT' | 'CIP' | 'DAP' | 'DDP') | null;
  /**
   * e.g. Shanghai
   */
  incotermPlace?: string | null;
  /**
   * e.g. 30% T/T in advance, 70% before shipment
   */
  paymentTerms?: string | null;
  /**
   * e.g. within 20 days of the order
   */
  delivery?: string | null;
  /**
   * Country or port. The customer name is never sent to suppliers.
   */
  destination?: string | null;
  documentsRequired?: string | null;
  notes?: string | null;
  subject?: string | null;
  /**
   * Written automatically. You can edit it before sending.
   */
  message?: string | null;
  rewriteMessage?: boolean | null;
  subjectAuto?: string | null;
  messageAuto?: string | null;
  /**
   * For our records only
   */
  order?: (number | null) | OrderMatch;
  fromEnquiry?: (number | null) | SupplierOrder;
  sentAt?: string | null;
  sentTo?: string | null;
  sendLog?: string | null;
  quoteCurrency?: ('USD' | 'CNY' | 'EUR') | null;
  quoteIncoterm?: ('EXW' | 'FCA' | 'FOB' | 'CFR' | 'CIF' | 'CPT' | 'CIP' | 'DAP' | 'DDP') | null;
  quoteIncotermPlace?: string | null;
  quoteValidUntil?: string | null;
  quotePaymentTerms?: string | null;
  quoteContact?: string | null;
  quoteSource?: ('supplier form' | 'email' | 'WeChat or phone') | null;
  quoteReceivedAt?: string | null;
  quoteNotes?: string | null;
  supplierReply?: string | null;
  quoteLog?: string | null;
  quoteToken?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Every payment received from a client, paid to a supplier, and every cost (freight, bank charges). Link it to the sale or the purchase order so the balances add up.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: number;
  date: string;
  direction: 'in' | 'out' | 'expense';
  category?:
    | (
        | 'freight'
        | 'customs and duties'
        | 'bank charges'
        | 'inspection and testing'
        | 'samples'
        | 'travel'
        | 'commission'
        | 'office'
        | 'other'
      )
    | null;
  amount: number;
  currency: 'USD' | 'CNY' | 'EUR';
  /**
   * The rate the bank used. Empty: the rate in Company details
   */
  usdRate?: number | null;
  amountUsd?: number | null;
  buyerDocument?: (number | null) | BuyerDocument;
  supplierOrder?: (number | null) | SupplierOrder;
  order?: (number | null) | OrderMatch;
  /**
   * Filled from the sale when empty
   */
  client?: (number | null) | Client;
  /**
   * Filled from the purchase order when empty
   */
  supplier?: (number | null) | Supplier;
  /**
   * e.g. the forwarder
   */
  paidTo?: string | null;
  method?: ('T/T bank transfer' | 'L/C' | 'PayPal' | 'Alipay' | 'WeChat Pay' | 'Cash' | 'Other') | null;
  /**
   * Transfer number or slip number
   */
  reference?: string | null;
  /**
   * Upload it under Documents first, then choose it here
   */
  proof?: (number | null) | TradeFile;
  notes?: string | null;
  void?: boolean | null;
  voidReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Upload any paper of a deal and link it to the client, the supplier and the order. It then shows on each of them.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trade-files".
 */
export interface TradeFile {
  id: number;
  /**
   * Short description; the file name when empty
   */
  title?: string | null;
  kind?:
    | (
        | 'client-order'
        | 'contract'
        | 'pi'
        | 'quotation'
        | 'invoice'
        | 'packing-list'
        | 'coa'
        | 'co'
        | 'bl'
        | 'payment'
        | 'photo'
        | 'correspondence'
        | 'other'
      )
    | null;
  date?: string | null;
  client?: (number | null) | Client;
  supplier?: (number | null) | Supplier;
  order?: (number | null) | OrderMatch;
  buyerDocument?: (number | null) | BuyerDocument;
  supplierOrder?: (number | null) | SupplierOrder;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Uploaded customer orders (private).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-files".
 */
export interface OrderFile {
  id: number;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  /**
   * Web address: /catalogue/<slug>/ (lower case, hyphens)
   */
  slug: string;
  /**
   * Shown on the public catalogue
   */
  published?: boolean | null;
  category: 'api' | 'excipient' | 'colour' | 'intermediate' | 'finished-dosage' | 'extract' | 'device' | 'other';
  /**
   * Therapeutic class, or colour type
   */
  productClass?: string | null;
  otherNames?: string | null;
  cas?: string | null;
  ciNumber?: string | null;
  grades?: ('EP' | 'USP' | 'BP' | 'JP' | 'ChP' | 'IP' | 'In-house')[] | null;
  /**
   * Private: manufacturers and their documents for this product
   */
  sources?:
    | {
        supplier: number | Supplier;
        /**
         * e.g. CEP, US DMF, WC, EU GMP
         */
        documents?: string | null;
        /**
         * e.g. permitted in: India, EU, USA
         */
        marketStatus?: string | null;
        details?: string | null;
        id?: string | null;
      }[]
    | null;
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Sort by "Valid until" to see what expires next.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supplier-certificates".
 */
export interface SupplierCertificate {
  id: number;
  /**
   * Filled in automatically
   */
  title?: string | null;
  supplier: number | Supplier;
  type:
    | 'cn-gmp'
    | 'cn-dml'
    | 'eu-gmp'
    | 'us-fda'
    | 'who-gmp'
    | 'cep'
    | 'us-dmf'
    | 'wc'
    | 'ipec-gmp'
    | 'iso-9001'
    | 'iso-13485'
    | 'iso-22000'
    | 'fssc-22000'
    | 'business-licence'
    | 'other';
  number?: string | null;
  issuer?: string | null;
  scope?: string | null;
  issued?: string | null;
  validUntil?: string | null;
  state?: string | null;
  /**
   * File name or Drive link of the copy we hold
   */
  sourceFile?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  type: 'rfq' | 'verification';
  status?: ('new' | 'replied' | 'quoted' | 'won' | 'closed') | null;
  name: string;
  company?: string | null;
  role?: string | null;
  country: string;
  email: string;
  /**
   * Phone or WhatsApp
   */
  phone?: string | null;
  service?: string | null;
  /**
   * Verification orders: supplier or product to check
   */
  supplier?: string | null;
  message: string;
  heardAbout?: string | null;
  consent: boolean;
  page?: string | null;
  utmFirst?: string | null;
  utmLast?: string | null;
  /**
   * Notification reached the mail relay
   */
  emailed?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'order-matches';
        value: number | OrderMatch;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'supplier-orders';
        value: number | SupplierOrder;
      } | null)
    | ({
        relationTo: 'buyer-documents';
        value: number | BuyerDocument;
      } | null)
    | ({
        relationTo: 'trade-files';
        value: number | TradeFile;
      } | null)
    | ({
        relationTo: 'payments';
        value: number | Payment;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'suppliers';
        value: number | Supplier;
      } | null)
    | ({
        relationTo: 'supplier-certificates';
        value: number | SupplierCertificate;
      } | null)
    | ({
        relationTo: 'order-files';
        value: number | OrderFile;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-matches_select".
 */
export interface OrderMatchesSelect<T extends boolean = true> {
  title?: T;
  customer?: T;
  client?: T;
  status?: T;
  orderFile?: T;
  typedMaterials?: T;
  rematch?: T;
  matchedAt?: T;
  readNote?: T;
  results?: T;
  lines?:
    | T
    | {
        requested?: T;
        cas?: T;
        grade?: T;
        quantity?: T;
        supplierCount?: T;
        matches?:
          | T
          | {
              supplier?: T;
              product?: T;
              matchedOn?: T;
              documents?: T;
              certificates?: T;
              id?: T;
            };
        id?: T;
      };
  notes?: T;
  documents?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  name?: T;
  country?: T;
  registrationNo?: T;
  address?: T;
  contactPerson?: T;
  email?: T;
  phone?: T;
  currency?: T;
  incoterm?: T;
  incotermPlace?: T;
  paymentTerms?: T;
  consignee?: T;
  notifyParty?: T;
  notes?: T;
  sales?: T;
  payments?: T;
  documents?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supplier-orders_select".
 */
export interface SupplierOrdersSelect<T extends boolean = true> {
  number?: T;
  kind?: T;
  status?: T;
  date?: T;
  supplier?: T;
  toEmail?: T;
  items?:
    | T
    | {
        material?: T;
        spec?: T;
        quantity?: T;
        unit?: T;
        unitPrice?: T;
        supplierProduct?: T;
        note?: T;
        quotedPrice?: T;
        moq?: T;
        leadTime?: T;
        quoteNote?: T;
        requested?: T;
        id?: T;
      };
  currency?: T;
  incoterm?: T;
  incotermPlace?: T;
  paymentTerms?: T;
  delivery?: T;
  destination?: T;
  documentsRequired?: T;
  notes?: T;
  subject?: T;
  message?: T;
  rewriteMessage?: T;
  subjectAuto?: T;
  messageAuto?: T;
  order?: T;
  fromEnquiry?: T;
  sentAt?: T;
  sentTo?: T;
  sendLog?: T;
  quoteCurrency?: T;
  quoteIncoterm?: T;
  quoteIncotermPlace?: T;
  quoteValidUntil?: T;
  quotePaymentTerms?: T;
  quoteContact?: T;
  quoteSource?: T;
  quoteReceivedAt?: T;
  quoteNotes?: T;
  supplierReply?: T;
  quoteLog?: T;
  quoteToken?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "buyer-documents_select".
 */
export interface BuyerDocumentsSelect<T extends boolean = true> {
  piNumber?: T;
  piDate?: T;
  validity?: T;
  status?: T;
  invoiceNumber?: T;
  invoiceDate?: T;
  buyerReference?: T;
  client?: T;
  buyerEmail?: T;
  buyerName?: T;
  buyerCountry?: T;
  buyerContact?: T;
  buyerAddress?: T;
  consignee?: T;
  notifyParty?: T;
  items?:
    | T
    | {
        description?: T;
        spec?: T;
        quantity?: T;
        unit?: T;
        unitPrice?: T;
        hsCode?: T;
        origin?: T;
        packages?: T;
        packageType?: T;
        netWeight?: T;
        grossWeight?: T;
        batchNo?: T;
        mfgDate?: T;
        expDate?: T;
        costPrice?: T;
        costSupplier?: T;
        costNote?: T;
        id?: T;
      };
  currency?: T;
  incoterm?: T;
  incotermPlace?: T;
  paymentTerms?: T;
  freight?: T;
  insurance?: T;
  discount?: T;
  portOfLoading?: T;
  portOfDischarge?: T;
  shipmentBy?: T;
  deliveryTime?: T;
  vessel?: T;
  blNumber?: T;
  shippingMarks?: T;
  remarks?: T;
  order?: T;
  internalNotes?: T;
  readyDate?: T;
  etd?: T;
  eta?: T;
  forwarder?: T;
  documentsSent?: T;
  followUp?: T;
  sendLog?: T;
  payments?: T;
  documents?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trade-files_select".
 */
export interface TradeFilesSelect<T extends boolean = true> {
  title?: T;
  kind?: T;
  date?: T;
  client?: T;
  supplier?: T;
  order?: T;
  buyerDocument?: T;
  supplierOrder?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  date?: T;
  direction?: T;
  category?: T;
  amount?: T;
  currency?: T;
  usdRate?: T;
  amountUsd?: T;
  buyerDocument?: T;
  supplierOrder?: T;
  order?: T;
  client?: T;
  supplier?: T;
  paidTo?: T;
  method?: T;
  reference?: T;
  proof?: T;
  notes?: T;
  void?: T;
  voidReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  published?: T;
  category?: T;
  productClass?: T;
  otherNames?: T;
  cas?: T;
  ciNumber?: T;
  grades?: T;
  sources?:
    | T
    | {
        supplier?: T;
        documents?: T;
        marketStatus?: T;
        details?: T;
        id?: T;
      };
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suppliers_select".
 */
export interface SuppliersSelect<T extends boolean = true> {
  name?: T;
  nameLocal?: T;
  country?: T;
  city?: T;
  address?: T;
  website?: T;
  email?: T;
  phone?: T;
  contactPerson?: T;
  wechat?: T;
  supplies?: T;
  status?: T;
  source?: T;
  documentsFolder?: T;
  rating?: T;
  problems?: T;
  notes?: T;
  orders?: T;
  payments?: T;
  documents?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supplier-certificates_select".
 */
export interface SupplierCertificatesSelect<T extends boolean = true> {
  title?: T;
  supplier?: T;
  type?: T;
  number?: T;
  issuer?: T;
  scope?: T;
  issued?: T;
  validUntil?: T;
  state?: T;
  sourceFile?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-files_select".
 */
export interface OrderFilesSelect<T extends boolean = true> {
  note?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  type?: T;
  status?: T;
  name?: T;
  company?: T;
  role?: T;
  country?: T;
  email?: T;
  phone?: T;
  service?: T;
  supplier?: T;
  message?: T;
  heardAbout?: T;
  consent?: T;
  page?: T;
  utmFirst?: T;
  utmLast?: T;
  emailed?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Printed on every enquiry, purchase order, proforma invoice, invoice and packing list. Fill in once.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trade-settings".
 */
export interface TradeSetting {
  id: number;
  /**
   * Optional. A PNG or JPG logo printed at the top of every document
   */
  logo?: (number | null) | Media;
  /**
   * The legal name of the company that buys and sells
   */
  companyName: string;
  /**
   * Full registered address, as on the business licence
   */
  address?: string | null;
  phone?: string | null;
  /**
   * Suppliers reply to this address
   */
  email?: string | null;
  website?: string | null;
  signatoryName?: string | null;
  signatoryTitle?: string | null;
  /**
   * One or more email addresses. Leave empty for no copy.
   */
  copyTo?: string | null;
  /**
   * Printed on the proforma invoice and the invoice: beneficiary, bank, account number, SWIFT, bank address
   */
  bankDetails?: string | null;
  /**
   * Pre-filled on new purchase orders
   */
  supplierPaymentTerms?: string | null;
  /**
   * Pre-filled on new proforma invoices
   */
  buyerPaymentTerms?: string | null;
  rateMode?: ('auto' | 'manual') | null;
  /**
   * Automatic mode fills this in; switch to "I type them myself" to use your own rate
   */
  cnyPerUsd?: number | null;
  usdPerEur?: number | null;
  ratesDate?: string | null;
  ratesSource?: string | null;
  ratesCheckedAt?: string | null;
  /**
   * Selling price = cost + this %. Pre-filled when a proforma invoice is made from the supplier prices; you can change it per item
   */
  defaultMargin?: number | null;
  aiMode?: boolean | null;
  aiModel?: ('claude-opus-5-5' | 'claude-sonnet-5-5' | 'claude-haiku-5-5' | 'gpt-5' | 'gpt-5-mini') | null;
  /**
   * A Claude key (console.anthropic.com) or an OpenAI key (platform.openai.com), matching the model above. Stored encrypted and never shown again. Leave empty to keep the current key
   */
  newAiKey?: string | null;
  aiKeyHint?: string | null;
  removeAiKey?: boolean | null;
  aiKeySealed?: string | null;
  /**
   * Pre-filled on new purchase orders
   */
  documentsRequired?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Totals for a period, balances, profit per sale. Download the Excel for the accountant.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts-overview".
 */
export interface AccountsOverview {
  id: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trade-settings_select".
 */
export interface TradeSettingsSelect<T extends boolean = true> {
  logo?: T;
  companyName?: T;
  address?: T;
  phone?: T;
  email?: T;
  website?: T;
  signatoryName?: T;
  signatoryTitle?: T;
  copyTo?: T;
  bankDetails?: T;
  supplierPaymentTerms?: T;
  buyerPaymentTerms?: T;
  rateMode?: T;
  cnyPerUsd?: T;
  usdPerEur?: T;
  ratesDate?: T;
  ratesSource?: T;
  ratesCheckedAt?: T;
  defaultMargin?: T;
  aiMode?: T;
  aiModel?: T;
  newAiKey?: T;
  aiKeyHint?: T;
  removeAiKey?: T;
  aiKeySealed?: T;
  documentsRequired?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts-overview_select".
 */
export interface AccountsOverviewSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}